accept text from stdin
asasine/spongebob pull request #16
Opened 2024-10-15 19:25 UTC by PlexSheep

See #13

2024-10-15 20:28 UTC, PlexSheep commented
Alright, I got it far enough that stdin for a lot of stuff will already work:

```bash
$ cat /etc/os-release | cargo run --bin spongebob -r -- -n
    Finished `release` profile [optimized] target(s) in 0.03s
     Running `target/release/spongebob -n`
NAMe="POP!_oS"
VerSioN="22.04 lTs"
Id=POp
Id_Like="uBUnTu DEbIAn"
PREtTY_nAmE="pop!_OS 22.04 lTs"
VersIoN_id="22.04"
hoMe_url="HttPs://Pop.SySteM76.COM"
sUPPorT_uRl="htTps://sUpPoRt.syStEm76.com"
bUg_repORT_url="HTtPs://giTHuB.COM/Pop-oS/PoP/issuES"
pRIVaCY_poLICy_url="HTTPS://sysTEM76.com/PRiVaCY"
VErsioN_CodENAmE=jAMMy
UbunTU_COdENamE=jAmMY
lOGo=dIsTRiBUTor-lOGo-POp-OS
```

Now, what I still want, is that I can get it to stream. What I mean by this is that the first process continuouly produces an output, and spongebob continuoulsy spongebobs it and prints it.

However, with the current status, this does not work:

```bash
$ yes | cargo run --bin spongebob -r -- -n
```

This is because of spongebob for the end of the stdin in `read_to_string`. An example of an application that can do streaming woud be `xxd`: `yes | xxd`. However, streaming will require changing a bit more than the input method.

2024-10-16 10:37 UTC, PlexSheep commented
Streaming is working too now. You can use the following rust script as stdin, and it will work.

```rs
//! just prints "foo" every 100ms
//!
//! used to test stdin streaming
fn main() {
    while true {
        println!("foo");
        std::thread::sleep_ms(100);
    }
}
```

2024-10-18 12:04 UTC, asasine requested changes
The implementation looks solid, thanks for contributing! I'd like to retain the `human_panic` functionality so changes there are needed. I'm not sure what the convention is for adding authors.

2024-10-18 12:04 UTC, asasine commented on Cargo.toml
> +	"Christoph J. Scherr <software@cscherr.de>",
Is it typical for PR contributions to include an additional author? This is my first open source project that's actually gotten another contributor.

2024-10-18 22:21 UTC, PlexSheep commented on src/main.rs
> +            repr = std::str::from_utf8(&buf[0..len])?.to_string();
It's possible, of course, but I'd argue that panic is not the right tool to deal with the case that the stdin is bad.

In my view, panic is the wrong tool for this kind of error, since it's just the user passing bad input into it. Using a panic here would be like the web server crashing, just because a user requested a site that does not exist (in HTTP that would be a 404 client error). In my opinion, simply writing that the input from stdin was not text would be more helpful than asking the user for a bug report, since this would not be a bug report. A panic would fit more when bad programming caused an error, not when a user caused one.

The Rust book has a [section](https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html) on panic vs results, but it's not clear from that what would strictly fit better.

So, I think some kind of result would help the user understand that they are not supposed to input non-text data, and a panic would just ask for a bug report, which would not make sense as the error would not come from a bug.

Regardless, I can remove the anyhow dependency if you prefer to have fewer deps. I think `std::io::Error` offers a functionality to give a string as an error now, we could use that instead.

2024-10-18 22:24 UTC, PlexSheep commented on Cargo.toml
> +	"Christoph J. Scherr <software@cscherr.de>",
I'm not sure too, as said in the commit msg. If this gets merged, then I did contribute a somewhat significant feature, but ultimately, it's your choice whether I'm declared co-author or not.

I can remove it no problem, really unsure about the etiquette with this.

2024-10-18 22:37 UTC, PlexSheep commented
I have removed the `anyhow` dependency and `main` no longer returns a result. Error handling is now done with `match` and prints an easily understandable error message to the stderr.

2024-10-19 11:27 UTC, asasine commented on src/main.rs
> +            repr = std::str::from_utf8(&buf[0..len])?.to_string();
Fair points about panic being wrong for unexpected input. What do you think about indicating the invalid input to stderr then continuing with what is valid?

2024-10-19 11:30 UTC, asasine commented on Cargo.toml
> +	"Christoph J. Scherr <software@cscherr.de>",
I noticed that `human_panic` adds all authors to the output when a crash occurs. I think tracking contributors in CONTRIBUTING.md and release notes would be fair instead of the Cargo.toml `authors` field. I created #22 to track that.

2024-10-19 12:14 UTC, PlexSheep commented on src/main.rs
> +            repr = std::str::from_utf8(&buf[0..len])?.to_string();
On the newer commits, I print an error message to stderr but do not continue.

If we were to continue after getting in-text data, what would be the expected behavior? Print the in-text data to stdout? I think just stopping with an error is the most reasonable. When the user puts in-text into the thing, something has gone wrong.

We might also filter the in-text data out, but that seems like unneeded complexity.

2024-10-19 21:43 UTC, asasine approved these changes
Looks good to me. I went ahead and pushed the changes to the `authors` field and resolved some merge conflicts stemming from #23

2024-10-19 21:44 UTC, merged